INSERT INTO [PPOK].[dbo].[notification]
(
	[patient_id], 
	[notification_type], 
	[scheduled_time],
	[send_status],
	[notification_message],
	[notification_response], 
	[object_active]
)
VALUES
(
	@PatientId, 
	@Type,
	@ScheduledTime,
	@Sent,
	@NotificationMessage,
	@NotificationResponse,
	1
)
